[project]
name = "lifet"
version = "0.1.0"
description = ""
authors = [
    {name = "Pablo Julian Garay de Leon",email = "leonmaing@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic (>=2.12.5,<3.0.0)",
    "google-genai (>=1.53.0,<2.0.0)",
    "openai (>=2.9.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "lifet", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
